//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Serialization;

namespace ValidaLco.Negocios.Connected_Services.Cliente {
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name="ResultadoConsultaRfc", Namespace="http://www.profact.com.mx/")]
    [Serializable()]
    public partial class ResultadoConsultaRfc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [NonSerialized()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        private bool CorrectoField;
        
        [OptionalField()]
        private string MensajeField;
        
        [OptionalField()]
        private string RfcField;
        
        private bool RegistradoEnElSatField;
        
        private bool EsRfcGenericoExtranjeroField;
        
        private bool EsRfcGenericoNacionalField;
        
        private bool AdheridoAlSistemaNacionalDeCoordinacionFiscalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [DataMember(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [DataMember(IsRequired=true)]
        public bool Correcto {
            get {
                return this.CorrectoField;
            }
            set {
                if ((this.CorrectoField.Equals(value) != true)) {
                    this.CorrectoField = value;
                    this.RaisePropertyChanged("Correcto");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [DataMember(EmitDefaultValue=false)]
        public string Rfc {
            get {
                return this.RfcField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcField, value) != true)) {
                    this.RfcField = value;
                    this.RaisePropertyChanged("Rfc");
                }
            }
        }
        
        [DataMember(IsRequired=true, Order=4)]
        public bool RegistradoEnElSat {
            get {
                return this.RegistradoEnElSatField;
            }
            set {
                if ((this.RegistradoEnElSatField.Equals(value) != true)) {
                    this.RegistradoEnElSatField = value;
                    this.RaisePropertyChanged("RegistradoEnElSat");
                }
            }
        }
        
        [DataMember(IsRequired=true, Order=5)]
        public bool EsRfcGenericoExtranjero {
            get {
                return this.EsRfcGenericoExtranjeroField;
            }
            set {
                if ((this.EsRfcGenericoExtranjeroField.Equals(value) != true)) {
                    this.EsRfcGenericoExtranjeroField = value;
                    this.RaisePropertyChanged("EsRfcGenericoExtranjero");
                }
            }
        }
        
        [DataMember(IsRequired=true, Order=6)]
        public bool EsRfcGenericoNacional {
            get {
                return this.EsRfcGenericoNacionalField;
            }
            set {
                if ((this.EsRfcGenericoNacionalField.Equals(value) != true)) {
                    this.EsRfcGenericoNacionalField = value;
                    this.RaisePropertyChanged("EsRfcGenericoNacional");
                }
            }
        }
        
        [DataMember(IsRequired=true, Order=7)]
        public bool AdheridoAlSistemaNacionalDeCoordinacionFiscal {
            get {
                return this.AdheridoAlSistemaNacionalDeCoordinacionFiscalField;
            }
            set {
                if ((this.AdheridoAlSistemaNacionalDeCoordinacionFiscalField.Equals(value) != true)) {
                    this.AdheridoAlSistemaNacionalDeCoordinacionFiscalField = value;
                    this.RaisePropertyChanged("AdheridoAlSistemaNacionalDeCoordinacionFiscal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="Valida LCOSoap", Namespace="http://www.profact.com.mx/", ConfigurationName="Cliente.ValidaLCOSoap")]
    public interface ValidaLCOSoap {
        
        // CODEGEN: Generating message contract since element name usuarioIntegrador from namespace http://www.profact.com.mx/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.profact.com.mx/ConsultaRfc", ReplyAction="*")]
        ConsultaRfcResponse ConsultaRfc(ConsultaRfcRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaRfcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaRfc", Namespace="http://www.profact.com.mx/", Order=0)]
        public ConsultaRfcRequestBody Body;
        
        public ConsultaRfcRequest() {
        }
        
        public ConsultaRfcRequest(ConsultaRfcRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.profact.com.mx/")]
    public partial class ConsultaRfcRequestBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public string usuarioIntegrador;
        
        [DataMember(EmitDefaultValue=false, Order=1)]
        public string rfcEmisor;
        
        [DataMember(EmitDefaultValue=false, Order=2)]
        public string rfcConsulta;
        
        public ConsultaRfcRequestBody() {
        }
        
        public ConsultaRfcRequestBody(string usuarioIntegrador, string rfcEmisor, string rfcConsulta) {
            this.usuarioIntegrador = usuarioIntegrador;
            this.rfcEmisor = rfcEmisor;
            this.rfcConsulta = rfcConsulta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaRfcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaRfcResponse", Namespace="http://www.profact.com.mx/", Order=0)]
        public ConsultaRfcResponseBody Body;
        
        public ConsultaRfcResponse() {
        }
        
        public ConsultaRfcResponse(ConsultaRfcResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [DataContract(Namespace="http://www.profact.com.mx/")]
    public partial class ConsultaRfcResponseBody {
        
        [DataMember(EmitDefaultValue=false, Order=0)]
        public ResultadoConsultaRfc ConsultaRfcResult;
        
        public ConsultaRfcResponseBody() {
        }
        
        public ConsultaRfcResponseBody(ResultadoConsultaRfc ConsultaRfcResult) {
            this.ConsultaRfcResult = ConsultaRfcResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidaLCOSoapChannel : ValidaLCOSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidaLCOSoapClient : System.ServiceModel.ClientBase<ValidaLCOSoap>, ValidaLCOSoap {
        
        public ValidaLCOSoapClient() {
        }
        
        public ValidaLCOSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidaLCOSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidaLCOSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidaLCOSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsultaRfcResponse ValidaLCOSoap.ConsultaRfc(ConsultaRfcRequest request) {
            return base.Channel.ConsultaRfc(request);
        }
        
        public ResultadoConsultaRfc ConsultaRfc(string usuarioIntegrador, string rfcEmisor, string rfcConsulta) {
            ConsultaRfcRequest inValue = new ConsultaRfcRequest();
            inValue.Body = new ConsultaRfcRequestBody();
            inValue.Body.usuarioIntegrador = usuarioIntegrador;
            inValue.Body.rfcEmisor = rfcEmisor;
            inValue.Body.rfcConsulta = rfcConsulta;
            ConsultaRfcResponse retVal = ((ValidaLCOSoap)(this)).ConsultaRfc(inValue);
            return retVal.Body.ConsultaRfcResult;
        }
    }
}
